-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 19:46:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_makev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_makev` ;

-- -----------------------------------------------------
-- Schema db_makev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_makev` DEFAULT CHARACTER SET utf8 ;
USE `db_makev` ;

-- -----------------------------------------------------
-- Table `db_makev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`users` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_makev`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admins` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admins_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_makev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '							';

CREATE INDEX `fk_admins_users1_idx` ON `db_makev`.`admins` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`admin_folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admin_folders` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admin_folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admins_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_folders_admins1`
    FOREIGN KEY (`admins_id`)
    REFERENCES `db_makev`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_folders_admins1_idx` ON `db_makev`.`admin_folders` (`admins_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`admin_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admin_images` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admin_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `admin_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_images_admin_folders1`
    FOREIGN KEY (`admin_folders_id`)
    REFERENCES `db_makev`.`admin_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_images_admin_folders1_idx` ON `db_makev`.`admin_images` (`admin_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`admin_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admin_videos` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admin_videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `admin_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_videos_admin_folders1`
    FOREIGN KEY (`admin_folders_id`)
    REFERENCES `db_makev`.`admin_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_videos_admin_folders1_idx` ON `db_makev`.`admin_videos` (`admin_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`admin_musics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admin_musics` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admin_musics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `admin_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_musics_admin_folders1`
    FOREIGN KEY (`admin_folders_id`)
    REFERENCES `db_makev`.`admin_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_musics_admin_folders1_idx` ON `db_makev`.`admin_musics` (`admin_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`clients` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `start_abonement` DATETIME NULL,
  `duration_abonement` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admins_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_makev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '							';

CREATE INDEX `fk_admins_users1_idx` ON `db_makev`.`clients` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`client_folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`client_folders` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`client_folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_folders_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `db_makev`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_folders_clients1_idx` ON `db_makev`.`client_folders` (`clients_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`client_musics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`client_musics` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`client_musics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `client_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_musics_client_folders1`
    FOREIGN KEY (`client_folders_id`)
    REFERENCES `db_makev`.`client_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_musics_client_folders1_idx` ON `db_makev`.`client_musics` (`client_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`client_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`client_videos` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`client_videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `client_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_videos_client_folders1`
    FOREIGN KEY (`client_folders_id`)
    REFERENCES `db_makev`.`client_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_videos_client_folders1_idx` ON `db_makev`.`client_videos` (`client_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`client_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`client_images` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`client_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `client_folders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_images_client_folders1`
    FOREIGN KEY (`client_folders_id`)
    REFERENCES `db_makev`.`client_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_images_client_folders1_idx` ON `db_makev`.`client_images` (`client_folders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`client_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`client_results` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`client_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_results_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `db_makev`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_results_clients1_idx` ON `db_makev`.`client_results` (`clients_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_makev`.`admin_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_makev`.`admin_results` ;

CREATE TABLE IF NOT EXISTS `db_makev`.`admin_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `admins_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_results_admins1`
    FOREIGN KEY (`admins_id`)
    REFERENCES `db_makev`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_results_admins1_idx` ON `db_makev`.`admin_results` (`admins_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
